upstream be {
    server be:8080;
}

server {
    listen 80;

    location /api/ {
        proxy_pass http://be;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        proxy_pass http://fe:80;
        proxy_set_header Host $host;
    }
}
