-- ============================================================
--  club 테이블에 kaggle_club_id 컬럼 추가
--  kaggle transfers.csv의 from_club_id / to_club_id 와 직접 매핑
-- ============================================================

ALTER TABLE club ADD COLUMN IF NOT EXISTS kaggle_club_id BIGINT;
CREATE UNIQUE INDEX IF NOT EXISTS idx_club_kaggle_id ON club (kaggle_club_id) WHERE kaggle_club_id IS NOT NULL;

-- ── Premier League ───────────────────────────────────────────
UPDATE club SET kaggle_club_id = 11   WHERE name = 'Arsenal FC';
UPDATE club SET kaggle_club_id = 989  WHERE name = 'AFC Bournemouth';
UPDATE club SET kaggle_club_id = 405  WHERE name = 'Aston Villa';
UPDATE club SET kaggle_club_id = 1148 WHERE name = 'Brentford FC';
UPDATE club SET kaggle_club_id = 1237 WHERE name = 'Brighton & Hove Albion';
UPDATE club SET kaggle_club_id = 1132 WHERE name = 'Burnley FC';
UPDATE club SET kaggle_club_id = 603  WHERE name = 'Cardiff City';
UPDATE club SET kaggle_club_id = 631  WHERE name = 'Chelsea FC';
UPDATE club SET kaggle_club_id = 873  WHERE name = 'Crystal Palace';
UPDATE club SET kaggle_club_id = 29   WHERE name = 'Everton FC';
UPDATE club SET kaggle_club_id = 931  WHERE name = 'Fulham FC';
UPDATE club SET kaggle_club_id = 1110 WHERE name = 'Huddersfield Town';
UPDATE club SET kaggle_club_id = 3008 WHERE name = 'Hull City';
UPDATE club SET kaggle_club_id = 677  WHERE name = 'Ipswich Town';
UPDATE club SET kaggle_club_id = 399  WHERE name = 'Leeds United';
UPDATE club SET kaggle_club_id = 1003 WHERE name = 'Leicester City';
UPDATE club SET kaggle_club_id = 31   WHERE name = 'Liverpool FC';
UPDATE club SET kaggle_club_id = 1031 WHERE name = 'Luton Town';
UPDATE club SET kaggle_club_id = 281  WHERE name = 'Manchester City';
UPDATE club SET kaggle_club_id = 985  WHERE name = 'Manchester United';
UPDATE club SET kaggle_club_id = 641  WHERE name = 'Middlesbrough FC';
UPDATE club SET kaggle_club_id = 762  WHERE name = 'Newcastle United';
UPDATE club SET kaggle_club_id = 1123 WHERE name = 'Norwich City';
UPDATE club SET kaggle_club_id = 703  WHERE name = 'Nottingham Forest';
UPDATE club SET kaggle_club_id = 1039 WHERE name = 'Queens Park Rangers';
UPDATE club SET kaggle_club_id = 1032 WHERE name = 'Reading FC';
UPDATE club SET kaggle_club_id = 350  WHERE name = 'Sheffield United';
UPDATE club SET kaggle_club_id = 180  WHERE name = 'Southampton FC';
UPDATE club SET kaggle_club_id = 512  WHERE name = 'Stoke City';
UPDATE club SET kaggle_club_id = 289  WHERE name = 'Sunderland AFC';
UPDATE club SET kaggle_club_id = 2288 WHERE name = 'Swansea City';
UPDATE club SET kaggle_club_id = 148  WHERE name = 'Tottenham Hotspur';
UPDATE club SET kaggle_club_id = 1010 WHERE name = 'Watford FC';
UPDATE club SET kaggle_club_id = 984  WHERE name = 'West Bromwich Albion';
UPDATE club SET kaggle_club_id = 379  WHERE name = 'West Ham United';
UPDATE club SET kaggle_club_id = 1071 WHERE name = 'Wigan Athletic';
UPDATE club SET kaggle_club_id = 543  WHERE name = 'Wolverhampton Wanderers';

-- ── Bundesliga ───────────────────────────────────────────────
UPDATE club SET kaggle_club_id = 10    WHERE name = 'Arminia Bielefeld';
UPDATE club SET kaggle_club_id = 15    WHERE name = 'Bayer 04 Leverkusen';
UPDATE club SET kaggle_club_id = 16    WHERE name = 'Borussia Dortmund';
UPDATE club SET kaggle_club_id = 18    WHERE name = 'Borussia Mönchengladbach';
UPDATE club SET kaggle_club_id = 23    WHERE name = 'Eintracht Braunschweig';
UPDATE club SET kaggle_club_id = 23826 WHERE name = 'RB Leipzig';
UPDATE club SET kaggle_club_id = 24    WHERE name = 'Eintracht Frankfurt';
UPDATE club SET kaggle_club_id = 269   WHERE name = 'Holstein Kiel';
UPDATE club SET kaggle_club_id = 27    WHERE name = 'Bayern Munich';
UPDATE club SET kaggle_club_id = 3     WHERE name = '1.FC Köln';
UPDATE club SET kaggle_club_id = 33    WHERE name = 'FC Schalke 04';
UPDATE club SET kaggle_club_id = 35    WHERE name = 'FC St. Pauli';
UPDATE club SET kaggle_club_id = 38    WHERE name = 'Fortuna Düsseldorf';
UPDATE club SET kaggle_club_id = 39    WHERE name = '1.FSV Mainz 05';
UPDATE club SET kaggle_club_id = 4     WHERE name = '1.FC Nuremberg';
UPDATE club SET kaggle_club_id = 41    WHERE name = 'Hamburger SV';
UPDATE club SET kaggle_club_id = 42    WHERE name = 'Hannover 96';
UPDATE club SET kaggle_club_id = 44    WHERE name = 'Hertha BSC';
UPDATE club SET kaggle_club_id = 4795  WHERE name = 'FC Ingolstadt 04';
UPDATE club SET kaggle_club_id = 533   WHERE name = 'TSG 1899 Hoffenheim';
UPDATE club SET kaggle_club_id = 60    WHERE name = 'SC Freiburg';
UPDATE club SET kaggle_club_id = 65    WHERE name = 'SpVgg Greuther Fürth';
UPDATE club SET kaggle_club_id = 79    WHERE name = 'VfB Stuttgart';
UPDATE club SET kaggle_club_id = 80    WHERE name = 'VfL Bochum';
UPDATE club SET kaggle_club_id = 82    WHERE name = 'VfL Wolfsburg';
UPDATE club SET kaggle_club_id = 86    WHERE name = 'SV Werder Bremen';
UPDATE club SET kaggle_club_id = 89    WHERE name = '1.FC Union Berlin';
UPDATE club SET kaggle_club_id = 2036  WHERE name = '1.FC Heidenheim 1846';
UPDATE club SET kaggle_club_id = 167   WHERE name = 'FC Augsburg';
UPDATE club SET kaggle_club_id = 105   WHERE name = 'SV Darmstadt 98';
UPDATE club SET kaggle_club_id = 127   WHERE name = 'SC Paderborn 07';

-- ── La Liga ──────────────────────────────────────────────────
UPDATE club SET kaggle_club_id = 1049  WHERE name = 'Valencia CF';
UPDATE club SET kaggle_club_id = 1050  WHERE name = 'Villarreal CF';
UPDATE club SET kaggle_club_id = 1084  WHERE name = 'Málaga CF';
UPDATE club SET kaggle_club_id = 1108  WHERE name = 'Deportivo Alavés';
UPDATE club SET kaggle_club_id = 12321 WHERE name = 'Girona FC';
UPDATE club SET kaggle_club_id = 1244  WHERE name = 'CD Leganés';
UPDATE club SET kaggle_club_id = 13    WHERE name = 'Atlético de Madrid';
UPDATE club SET kaggle_club_id = 131   WHERE name = 'FC Barcelona';
UPDATE club SET kaggle_club_id = 142   WHERE name = 'Real Zaragoza';
UPDATE club SET kaggle_club_id = 150   WHERE name = 'Real Betis Balompié';
UPDATE club SET kaggle_club_id = 1531  WHERE name = 'Elche CF';
UPDATE club SET kaggle_club_id = 1533  WHERE name = 'SD Eibar';
UPDATE club SET kaggle_club_id = 16795 WHERE name = 'Granada CF';
UPDATE club SET kaggle_club_id = 237   WHERE name = 'RCD Mallorca';
UPDATE club SET kaggle_club_id = 2448  WHERE name = 'Sporting Gijón';
UPDATE club SET kaggle_club_id = 2497  WHERE name = 'Real Oviedo';
UPDATE club SET kaggle_club_id = 2687  WHERE name = 'Cádiz CF';
UPDATE club SET kaggle_club_id = 3302  WHERE name = 'UD Almería';
UPDATE club SET kaggle_club_id = 331   WHERE name = 'CA Osasuna';
UPDATE club SET kaggle_club_id = 3368  WHERE name = 'Levante UD';
UPDATE club SET kaggle_club_id = 366   WHERE name = 'Real Valladolid CF';
UPDATE club SET kaggle_club_id = 367   WHERE name = 'Rayo Vallecano';
UPDATE club SET kaggle_club_id = 368   WHERE name = 'Sevilla FC';
UPDATE club SET kaggle_club_id = 3709  WHERE name = 'Getafe CF';
UPDATE club SET kaggle_club_id = 418   WHERE name = 'Real Madrid';
UPDATE club SET kaggle_club_id = 472   WHERE name = 'UD Las Palmas';
UPDATE club SET kaggle_club_id = 5358  WHERE name = 'SD Huesca';
UPDATE club SET kaggle_club_id = 621   WHERE name = 'Athletic Bilbao';
UPDATE club SET kaggle_club_id = 681   WHERE name = 'Real Sociedad';
UPDATE club SET kaggle_club_id = 714   WHERE name = 'RCD Espanyol Barcelona';
UPDATE club SET kaggle_club_id = 897   WHERE name = 'Deportivo de La Coruña';
UPDATE club SET kaggle_club_id = 940   WHERE name = 'Celta de Vigo';
UPDATE club SET kaggle_club_id = 993   WHERE name = 'Córdoba CF';

-- ── Serie A ──────────────────────────────────────────────────
UPDATE club SET kaggle_club_id = 1005  WHERE name = 'US Lecce';
UPDATE club SET kaggle_club_id = 1025  WHERE name = 'Bologna FC 1909';
UPDATE club SET kaggle_club_id = 1038  WHERE name = 'UC Sampdoria';
UPDATE club SET kaggle_club_id = 1047  WHERE name = 'Como 1907';
UPDATE club SET kaggle_club_id = 12    WHERE name = 'AS Roma';
UPDATE club SET kaggle_club_id = 1210  WHERE name = 'AS Livorno';
UPDATE club SET kaggle_club_id = 130   WHERE name = 'Parma Calcio 1913';
UPDATE club SET kaggle_club_id = 1387  WHERE name = 'AC Siena';
UPDATE club SET kaggle_club_id = 1390  WHERE name = 'Cagliari Calcio';
UPDATE club SET kaggle_club_id = 1429  WHERE name = 'AC Cesena';
UPDATE club SET kaggle_club_id = 1627  WHERE name = 'Calcio Catania';
UPDATE club SET kaggle_club_id = 19    WHERE name = 'Brescia Calcio';
UPDATE club SET kaggle_club_id = 2239  WHERE name = 'US Cremonese';
UPDATE club SET kaggle_club_id = 252   WHERE name = 'Genoa CFC';
UPDATE club SET kaggle_club_id = 2722  WHERE name = 'SPAL';
UPDATE club SET kaggle_club_id = 276   WHERE name = 'Hellas Verona';
UPDATE club SET kaggle_club_id = 2919  WHERE name = 'AC Monza';
UPDATE club SET kaggle_club_id = 2921  WHERE name = 'Delfino Pescara 1936';
UPDATE club SET kaggle_club_id = 3522  WHERE name = 'Spezia Calcio';
UPDATE club SET kaggle_club_id = 380   WHERE name = 'US Salernitana 1919';
UPDATE club SET kaggle_club_id = 398   WHERE name = 'SS Lazio';
UPDATE club SET kaggle_club_id = 4083  WHERE name = 'FC Crotone';
UPDATE club SET kaggle_club_id = 410   WHERE name = 'Udinese Calcio';
UPDATE club SET kaggle_club_id = 416   WHERE name = 'Torino Calcio';
UPDATE club SET kaggle_club_id = 4171  WHERE name = 'Benevento Calcio';
UPDATE club SET kaggle_club_id = 4172  WHERE name = 'Pisa Sporting Club';
UPDATE club SET kaggle_club_id = 430   WHERE name = 'ACF Fiorentina';
UPDATE club SET kaggle_club_id = 458   WHERE name = 'US Palermo';
UPDATE club SET kaggle_club_id = 46    WHERE name = 'Inter Milan';
UPDATE club SET kaggle_club_id = 5     WHERE name = 'AC Milan';
UPDATE club SET kaggle_club_id = 506   WHERE name = 'Juventus FC';
UPDATE club SET kaggle_club_id = 607   WHERE name = 'Venezia FC';
UPDATE club SET kaggle_club_id = 6195  WHERE name = 'SSC Napoli';
UPDATE club SET kaggle_club_id = 6574  WHERE name = 'US Sassuolo';
UPDATE club SET kaggle_club_id = 749   WHERE name = 'FC Empoli';
UPDATE club SET kaggle_club_id = 800   WHERE name = 'Atalanta BC';
UPDATE club SET kaggle_club_id = 862   WHERE name = 'Chievo Verona';
UPDATE club SET kaggle_club_id = 8970  WHERE name = 'Frosinone Calcio';

-- ── Ligue 1 ─────────────────────────────────────────────────
UPDATE club SET kaggle_club_id = 10004 WHERE name = 'Paris FC';
UPDATE club SET kaggle_club_id = 1041  WHERE name = 'Olympique Lyon';
UPDATE club SET kaggle_club_id = 1082  WHERE name = 'LOSC Lille';
UPDATE club SET kaggle_club_id = 1095  WHERE name = 'ESTAC Troyes';
UPDATE club SET kaggle_club_id = 1147  WHERE name = 'AC Ajaccio';
UPDATE club SET kaggle_club_id = 1158  WHERE name = 'FC Lorient';
UPDATE club SET kaggle_club_id = 1159  WHERE name = 'AS Nancy-Lorraine';
UPDATE club SET kaggle_club_id = 1160  WHERE name = 'Nîmes Olympique';
UPDATE club SET kaggle_club_id = 1162  WHERE name = 'SM Caen';
UPDATE club SET kaggle_club_id = 1416  WHERE name = 'Amiens SC';
UPDATE club SET kaggle_club_id = 14171 WHERE name = 'FC Évian Thonon Gaillard';
UPDATE club SET kaggle_club_id = 1420  WHERE name = 'Angers SCO';
UPDATE club SET kaggle_club_id = 1421  WHERE name = 'Stade Reims';
UPDATE club SET kaggle_club_id = 1423  WHERE name = 'Valenciennes FC';
UPDATE club SET kaggle_club_id = 162   WHERE name = 'AS Monaco';
UPDATE club SET kaggle_club_id = 244   WHERE name = 'Olympique Marseille';
UPDATE club SET kaggle_club_id = 273   WHERE name = 'Stade Rennais FC';
UPDATE club SET kaggle_club_id = 290   WHERE name = 'AJ Auxerre';
UPDATE club SET kaggle_club_id = 2969  WHERE name = 'Dijon FCO';
UPDATE club SET kaggle_club_id = 347   WHERE name = 'FC Metz';
UPDATE club SET kaggle_club_id = 3524  WHERE name = 'Clermont Foot 63';
UPDATE club SET kaggle_club_id = 3558  WHERE name = 'GFC Ajaccio';
UPDATE club SET kaggle_club_id = 3911  WHERE name = 'Stade Brestois 29';
UPDATE club SET kaggle_club_id = 40    WHERE name = 'FC Girondins Bordeaux';
UPDATE club SET kaggle_club_id = 415   WHERE name = 'FC Toulouse';
UPDATE club SET kaggle_club_id = 417   WHERE name = 'OGC Nice';
UPDATE club SET kaggle_club_id = 583   WHERE name = 'Paris Saint-Germain';
UPDATE club SET kaggle_club_id = 595   WHERE name = 'SC Bastia';
UPDATE club SET kaggle_club_id = 618   WHERE name = 'AS Saint-Étienne';
UPDATE club SET kaggle_club_id = 667   WHERE name = 'RC Strasbourg Alsace';
UPDATE club SET kaggle_club_id = 738   WHERE name = 'Le Havre AC';
UPDATE club SET kaggle_club_id = 750   WHERE name = 'FC Sochaux-Montbéliard';
UPDATE club SET kaggle_club_id = 826   WHERE name = 'RC Lens';
UPDATE club SET kaggle_club_id = 855   WHERE name = 'EA Guingamp';
UPDATE club SET kaggle_club_id = 969   WHERE name = 'Montpellier HSC';
UPDATE club SET kaggle_club_id = 995   WHERE name = 'FC Nantes';
