plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.5'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'transfer'
version = '0.0.1-SNAPSHOT'
description = 'BE'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // Web
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'

    // Jackson (JSON 직렬화/역직렬화)
    implementation 'com.fasterxml.jackson.core:jackson-databind'

    // JPA
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    // Cache abstraction (@Cacheable, NoOpCacheManager 등)
    implementation 'org.springframework.boot:spring-boot-starter-cache'

    // Redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    // PostgreSQL
    runtimeOnly 'org.postgresql:postgresql'

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // Configuration Processor (@ConfigurationProperties 자동완성)
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

    // DevTools
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    // Test
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testRuntimeOnly 'com.h2database:h2'
}

tasks.named('test') {
    useJUnitPlatform()
}